kind: pipeline
name: default

workspace:
  base: /go
  path: src/drone-demo

steps:
- name: run
  image: golang:alpine
  commands:
  - go get
  - go build
  - ./drone-demo

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
  - tag
  - promote
  - rollback
